import Link from "next/link";
import React from "react";

export default function TermsAndConditionPage() {
  return (
    <main className="pt-28 sm:pt-36 pb-8 md:pt-40 lg:pt-48 2xl:pt-52 md:pb-20 bg-[url('/assets/images/team_bg.webp')] bg-contain bg-no-repeat lg:bg-repeat">
      <section className="main-container">
        <h5 className="uppercase font-jost font-bold text-gradient text-lg sm:text-2xl md:text-3xl tracking-wider sm:pb-3 md:text-center">
          Terms And Conditions
        </h5>

        {/* important notice */}
        <ImportantNotice />
      </section>
    </main>
  );
}

const ImportantNotice = () => {
  return (
    <div className="my-4 sm:my-5 md:my-7 lg:my-9 xl:py-11 2xl:py-10 font-poppins flex flex-col gap-3 md:gap-5 lg:gap-7 xl:gap-8">
      <h3 className="text-white text-lg md:text-xl xl:text-2xl 2xl:text-3xl font-jost font-bold">
        {/* Important Notice: */}
      </h3>

      <div className="flex flex-col gap-2.5 md:gap-3 xl:gap-4 2xl:gap-5">
        <p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg">
          The Services, as defined below, are controlled, operated and administered by the Company, as defined below. All inquiries may be directed to support@katanainu.com.
        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          These Website Terms and Conditions (the “Terms”) constitute a legally binding agreement between you (“you”, “your” or “User”) and. Katana Inu Operating Katana Marketplace LTD Limited, a company incorporated in the British Virgin Islands (“Company”, “us”, “we”), which operates the Site www.katanainu.com, the mobile website, and all other media form (collectively, the “Site”) and related Services under license from Katana Marketplace Ltd
c/o Craigmuir Chambers Road Town, Tortola VG 1110 BRITISH VIRGIN ISLANDS company and the owner of the Game’s intellectual property.
        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          The Site provides, inter alia, information on and relating to the “Katana Inu” game and its “Katana Inu” component (the “Game”). In addition, there are certain services you may access through the Site (collectively, the “Services”). The Game is under development and, once launched, will include components that are centralized and decentralized. The Game is partly a product of the Company. Specifically, the game world and graphics and interface that users interact with to engage with the game world and others in game players will be products of the Company.
        </p>
        <p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg">
          We are using Thirdweb.com for our wallets https://thirdweb.com/terms please read also these terms and conditions.
        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          The decentralized components of the Game will include one or more self-executing programs designed to automate specific actions and transactions required within the Game ecosystem (each, a “Smart Contract”). These Smart Contracts will be fully compliant with the provisions outlined in these Terms. They enable users, including but not limited to, owning, transferring, battling, and creating unique digital assets within the Game. These digital assets may include plots of land, items, or other non-fungible tokens (NFTs), which can be visualized and interacted with by players through the Site. Smart Contracts will operate on decentralized networks such as the Thirdweb.com platform to facilitate these transactions and interactions the Wallets. We will also use different platforms like IMX Passport, Sequence and more.
        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          The existing and planned versions of the Katana Inu game are a fictionalised depiction of certain historical figures and historical periods. The source historical content on which the game is based, which it does and will depict, are in the public domain. This game and its content have no affiliation or connection to any existing television, radio, or other media content depicting the same or similar historical events or figures. The game and all related content (including promotional content), copyright and other rights property of Katana Marketpalce LTD  are used under license from the lawful owners.
        </p>
        <p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg">
         WE ARE ONLY WILLING TO MAKE THE SERVICES AVAILABLE TO YOU IF YOU ACCEPT ALL OF THESE TERMS. BY USING THE SERVICES, OR ANY OTHER OFFICIAL COMPANY’S PRODUCT, YOU ARE CONFIRMING THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY ALL OF THESE TERMS. IF YOU DO NOT AGREE AND/OR ACCEPT ALL OF THESE TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE, THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.
        </p>
        {/* <ul className="list-disc flex flex-col gap-1">
          <li className="text-xs md:text-sm xl:text-base text-white">
            A full XP and player progression system
          </li>
          <li className="text-xs md:text-sm xl:text-base text-white">
            Class-based characters with unique mechanics
          </li>
          <li className="text-xs md:text-sm xl:text-base text-white">
            A wide range of backend upgrades built completely from scratch
          </li>
          <li className="text-xs md:text-sm xl:text-base text-white">
            Core gameplay improvements, including better cooldowns, kill
            systems, and responsiveness
          </li>
        </ul> */}
        <p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg">
          By accessing or using the game, you confirm that you are at least 18 years old or have reached the age of legal majority in your country of residence. If you are at least 13 years old but under the age of legal majority, you may only access and use the game with the consent and supervision of your parent or legal guardian. In such cases, you represent that your parent or legal guardian has read, understood, and agreed to these Terms on your behalf and assumes full responsibility for your use of the game, including any payments made. We reserve the right to request verifiable parental consent at any time and may suspend or terminate access to the game if such consent is not provided or if these Terms are breached.
        </p>
        <p className="text-xs md:text-sm xl:text-base text-white">
          
YOU EXPRESSLY AGREE THAT YOU ACCESS AND USE OF THE SITE OR THE SERVICES CONSTITUTES YOUR WAIVER OF ANY CLASS RIGHTS IN RESPECT OF CLASS ACTIONS IN THE UNITED STATES OF AMERICA OR OTHER JURISDICTIONS WHERE THE SAME OR SIMILAR RIGHTS MAY BE AVAILABLE. YOU AGREE TO RESOLVE ANY DISPUTES ARISING UNDER OR IN CONNECTION WITH THESE TERMS, THE SITE, THE GAME, OR ANY MATTER RELATING HERETO THAT INVOLVED US BY BINDING ARBITRATION PURSUANT TO THE DISPUTE RESOLUTION CLAUSE 22 OF THIS AGREEMENT.

        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          The form and nature of the Services, and all information posted on the Site, are subject to reasonable changes in accordance with these Terms. Changes to the Services or the Terms will only occur for specific reasons, including: (A) ensuring compliance with applicable laws and/or reflecting changes in relevant laws and regulatory requirements, (B) performing temporary maintenance, fixing bugs, implementing technical adjustments, and making improvements, (C) updating or upgrading the Product/Service, environment, user interface, or related functionalities, or (D) addressing illegal or harmful activities, including the use of unauthorized programs or services in breach of these Terms. Any such changes will be communicated to users in advance through their registered email address or by a prominent notification on the Site or App, clearly explaining the nature and reasons for the changes.
        </p>

        <p className="text-xs md:text-sm xl:text-base text-white">
          Changes to these Terms shall not take effect without the user’s explicit consent. Upon implementation, users will be required to review and accept the updated Terms through a mandatory notification or popup on the Site or App. A minimum notice period of 30 days will be provided for users to review and decide. If a user does not accept the changes, they will retain the right to terminate their agreement and cease use of the Services without penalty within the notice period. The Company will make such changes by posting them here. You should check this page periodically for such changes. You can determine when these Terms were last revised by referring to the “LAST UPDATED” legend at the top of these Terms. Your continued access of the Site after such changes conclusively demonstrates your acceptance of those changes.

The information on the Site, the App, and the Smart Contracts are not intended for distribution to any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation, or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, any persons who access the Site and/or the App while breaking their local laws are doing it on their own initiative and will have to deal with the consequences when applicable. We reserve the right, at any time and from time to time, to modify or discontinue the Site, Services, or Game, in whole or in part, for the specific reasons outlined above. We also reserve the right to charge fees in connection with the use of the Services where approved by the user; modify and/or waive any fees charged in connection with the Services; and/or offer opportunities to some or all users of the Services.

        </p>
<p className="text-xs md:text-sm xl:text-base text-white">In these Terms, “Affiliated Entities” means any direct or indirect parents, subsidiaries, sponsors, or affiliates of the Company. You agree that neither we nor any Affiliated Entities shall be liable to you or to any third party for any modification, suspension or discontinuance of the Site, in whole or in part, or of any Service, information and materials contained herein, software used to make the Site, or feature or product offered through the Site.</p>
        <p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg mt-1 md:mt-1.5 lg:mt-2 xl:mt-2.5">
          IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU SHOULD DISCONTINUE USE IMMEDIATELY.
        </p>


<p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg mt-1 md:mt-1.5 lg:mt-2 xl:mt-2.5">
          ACCOUNT CREATIONS.
        </p>
        <p className="text-xs md:text-sm xl:text-base text-white">1.1. To access certain Services, including, without limitation, payment using credit cards or other forms of electronic payment you may be asked to provide certain registration details or other information.</p>

<p className="text-xs md:text-sm xl:text-base text-white">1.2. To create an Account to access certain Services, you must:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Be at least 18 years of age or are of the legal age to form binding contract under the applicable laws to register. Comply with all obligations as set out in these Terms and in any applicable laws. 1.3. Your Account belongs to you, and you are solely responsible for anything that happens through your Account, unless otherwise for the reasons of closure, hacks, or misuse. For the purposes of this Section 1.3, it shall be the sole responsibility of the User to avoid any unauthorized use or access of the Account.</p>

<p className="text-xs md:text-sm xl:text-base text-white">1.4. The Company reserves the right, at its sole discretion, to refuse your application for registration or disable any username, password, or other identifier, whether chosen by you or provided by us, in the event of a material breach of the provisions outlined within these Terms. For minor breaches, as reasonably evaluated, the Company will first issue a warning, which may include a temporary suspension of access to the Site, App, or Services. Repeated minor breaches, or any further violations after a warning, may escalate to constitute a material breach, granting the Company the right to terminate your access to the Services and any existing obligations under these Terms. Such actions will be taken in compliance with applicable laws and with due regard to fairness and proportionality.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> PARTY COMMUNICATIONS. 2.1. Notices to you may be made via by e-mail, by regular mail, (in the latter two situations, via the most recent address that we have on file).</p>

<p className="text-xs md:text-sm xl:text-base text-white">2.2. By providing your contact information and engaging with the Site or Services, you consent to receive communications from us strictly for contractual purposes. We will communicate with you electronically via email or by other means for matters directly related to the execution, modification, or fulfillment of these Terms. Any advertising or promotional communications will require your separate, explicit consent and will not be governed by these Terms.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> ADDITIONAL TERMS. 3.1. If you choose to access particular Services that are available via the Site, you may be provided with separate terms and conditions (& Additional Terms& ) related to and in addition to these Terms at the time you chose to access said particular Service. Some of the Additional Terms you will be provided with when accessing your chosen service may supersede these Terms and will be drawn to your attention, where applicable. Access to and use of relevant Services shall be limited to the specified users identified in the Additional Terms for each Service.</p>

<p className="text-xs md:text-sm xl:text-base text-white">3.2. You may not use the Site or receive relevant Services except as expressly provided in these Terms or any applicable Additional Terms. By creating an account or actively agreeing to these Terms through a clear opt-in mechanism before accessing any part of the Site or Services, you confirm that you have reviewed, understood, and accepted the applicable Terms and Additional Terms. Access to the Site alone, without such agreement, does not constitute acceptance of these Terms. Users who do not agree to the Terms or Additional Terms will be restricted from accessing certain functionalities or Services requiring such acceptance.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> CHANGES TO OUR SITE. The Company reserves the right, at its sole discretion, to modify, suspend, withdraw, discontinue, or make changes to any aspect of the Site as may be reasonably necessary to ensure compliance with applicable laws, improve functionality, address security concerns, or enhance user experience. Any such changes shall be communicated to all registered users through a notification, specifying the nature, scope, and implications of the modifications. For any material changes that may significantly impact users&  rights, obligations, or the functionality of the Site, the Company shall require users to explicitly accept the updated Terms or modifications prior to further use of the Site.</p>

<p className="text-xs md:text-sm xl:text-base text-white">While the Company endeavors to keep the content on the Site accurate and current, some content may become outdated. The Company is not obligated to update such content unless required to do so by applicable law or to address critical operational needs. The availability of the Site may also be temporarily suspended or restricted for maintenance, upgrades, or other operational purposes. Where feasible, the Company shall provide reasonable advance notice of such interruptions to minimize any inconvenience to users.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> INTELLECTUAL PROPERTY. 5.1. The Game, Site, and related intellectual property are owned by Katana Marketplace LTD., a company incorporated in BVI, and licensed to Katana Inu Operating Limited (BVI) for the purpose of operation, management, and user access. These Terms govern your use of the Services as operated by the BVI entity under the said license.</p>

<p className="text-xs md:text-sm xl:text-base text-white">Unless otherwise indicated, the Site, the Game, App and the Smart Contracts are our proprietary property and all source code, databases, functionality, software, website design, audio, video, text, photographs, and graphics on the Site (collectively, the & Content& ) and the trademarks, service marks, and logos contained therein (& Marks& ) are owned and controlled by us or are licensed and/ or assigned to us, and are protected by trademark and intellectual property law and unfair competition and practices legislations in appropriate jurisdictions. The Content and Marks are provided on the Site & AS IS&  for your information and used in accordance with these Terms only. Except as expressly provided in these Terms, no part of the Site and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited or for any commercial purpose whatsoever, without our express prior written permission.</p>

<p className="text-xs md:text-sm xl:text-base text-white">5.2. Provided that you are eligible to use the Site, you are granted, a limited, non-exclusive, non-transferable, non-assignable, and revocable license to access any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.</p>

<p className="text-xs md:text-sm xl:text-base text-white">5.3. You should assume that everything you see or read on the Site is copyrighted unless otherwise noted and may not be used except as provided in these Terms or in the text on the Site without the written permission of Company. Company neither warrants nor represents that your use of materials displayed on Company& s Sites will not infringe rights of third parties not owned by or affiliated with Company. Images, photographs, or illustrations displayed on the Site are either the property of, or used with permission by the Company. The use of these materials by you, or anyone else authorized by you, is prohibited unless specifically permitted by these Terms or specific permission provided elsewhere on the Site. Any unauthorized use of the images may violate copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes.</p>

<p className="text-xs md:text-sm xl:text-base text-white">5.4. For the sake of clarity, you understand and agree: (i) that any & purchase&  of the NFT& s, does not give you any rights or licenses in or to the Content and the Marks other than those expressly contained in these Terms; and (ii) that you do not have the right to reproduce, distribute, or otherwise commercialize any elements of the Content and the Marks, in any way without the Company& s prior written consent in each case, which consent the Company may withhold in its sole and absolute discretion.</p>

<p className="text-xs md:text-sm xl:text-base text-white">5.5. Provided that you own, or get permission from someone who owns a digital asset, you are granted a limited license to create fan-art which can be used commercially given that you follow the terms set herein:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Fan artwork must not use official Game& s assets (including but not limited to, the Product& s logo or associated logos) but creating derivate non-commercial official Game& s assets as inspiration is acceptable. The artwork must clearly state & Katana Inu Fanart& , link to https://www.katanainu.com/, and link directly to the digital asset that is being used for inspiration. A Game associated NFT can be used to generate a maximum of USD $10,000 in revenue before an official license agreement has to be signed. The revenue can come from either fanart (tokenized or physical) or merchandise (t-shirts, mugs, hoodies, etc.). Creating original fanart without monetizing it is acceptable without any license or ownership. 5.6. PLEASE NOTE THAT UNAUTHORIZED USE OF THE SITE OR ANY CONTENT ON THE SITE, GAME, APP, OR SMART CONTRACTS (INCLUDING WITHOUT LIMITATION ANY SOFTWARE MADE AVAILABLE THROUGH THE SITE) MAY IN PARTICULAR JURISDICTIONS RESULT IN MONETARY DAMAGES AND OTHER CIVIL AND CRIMINAL PENALTIES INCLUDING WITHOUT LIMITATION, FOR COPYRIGHT INFRINGEMENT.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> LIMITED LICENSE. 6.1. Subject to these Terms, we grant you a limited, individual, nonexclusive, non-transferable, revocable license to access and use the Site and the Services in such form, as they may exist from time to time. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.</p>

<p className="text-xs md:text-sm xl:text-base text-white">6.2. Subject to these Terms, you may use the Site for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on our Site, except as follows:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials. You may store files that are automatically cached by your Web browser for display enhancement purposes. You may print or download one copy of a reasonable number of pages of the Site for your own personal, non-commercial use and not for further reproduction, publication or distribution: and If we provide desktop, mobile or other applications for download, you may download a single copy to your computer or mobile device solely for your own personal, non-commercial use. 6.3. No right, title or interest in or to the Site or any Content on the Site is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Site not expressly permitted by these Terms is a breach of these Terms and may violate copyright, trademark and other laws.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> FEE AND PAYMENT. 7.1. Any purchases, trade, or sell of the NFTs from the Site, or App or associated marketplaces will be done through smart contracts on a blockchain using a digital asset wallet like Metamask or Thirdweb Wallet or Sequence etc. Any financial transactions that you engage in will be conducted solely through the Blockchain via a digital asset wallet such as MetaMask. We will have no insight into or control over these payments or transactions, nor do we have the ability to reverse any transactions. With that in mind, we will have no liability to you or to any third party for any claims or damages that may arise as a result of any transactions that you engage in via the Site and/or the App or using the Smart Contracts, or any other transactions that you conduct via the Polygon network.</p>

<p className="text-xs md:text-sm xl:text-base text-white">For Wallets please read this Terms and Conditions of Thirdweb: https://thirdweb.com/terms if you own a wallet of Katanainu Game via Thirdweb as its a thirdparty we are using. Every User is self custodial of his wallet. Means if you got hacked, or lose your account, we are not responsible for this, you need to contact thirdweb.com</p>

<p className="text-xs md:text-sm xl:text-base text-white">7.2. The Polygon network and the Immutable X (IMX) platform require and other Plattforms we are working with like Skale, Avalanche, SUI, and other blockchains as we are a multichain project, the payment of a transaction fee (a &quot;Gas Fee&quot;) for each transaction that occurs on their respective networks. The Gas Fee funds the decentralized networks of computers that operate these blockchain platforms. The Company is not affiliated with Polygon or Immutable X and does not control or influence their operations, terms, or conditions. By using these networks, you acknowledge and agree that you are entering into a separate agreement with all of our blockchain and non-blockchain integrations, as applicable, subject to their respective terms and conditions. You are solely responsible for reviewing and agreeing to the terms of these third-party platforms before conducting any transactions via the App. Consequently, you will be required to pay a Gas Fee for each transaction executed on these platforms.</p>

<p className="text-xs md:text-sm xl:text-base text-white">7.3. In addition to the Gas Fee, each time you utilize a Smart Contract to conduct a transaction with another user via the App, you authorize us to collect a commission of a percentage determined by the Game development team of the total value of that transaction (each, a & Commission& ). You acknowledge and agree that the Commission will be transferred directly to us through the Polygon Network as a part of the transaction.</p>

<p className="text-xs md:text-sm xl:text-base text-white">7.4. As between us, you will be solely responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority (collectively, & Taxes& ) associated with your use of the App (including, without limitation, any Taxes that may become payable as the result of your ownership, or transfer of the NFTs). Except for income taxes levied on the Company, you: (i) will pay or reimburse us for all national, federal, state, local, or other taxes and assessments of any jurisdiction, including value-added taxes and taxes as required by international tax treaties, customs or other import or export taxes, and amounts levied in lieu thereof based on charges set, services performed or payments made hereunder, as are now or hereafter may be imposed under the authority of any national, state, local or any other taxing jurisdiction; and (ii) shall not be entitled to deduct the amount of any such taxes, duties or assessments from payments made to us pursuant to these Terms.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> NFTs Sale. 8.1. The NFTs are available for sale for the first time on the marketplace through sales or auctions as Minting Page or in secondary market on different Marketplaces like Opensea.</p>

<p className="text-xs md:text-sm xl:text-base text-white">8.2. Purchasing the NFTs with a Fixed Price. If it is made available, you may enter into a fixed price sale transaction whereby we have listed such NFTs for sale on the marketplace at a fixed sale price and you may enter into a legally binding agreement to purchase such NFT by committing to buy the NFTs at the specified sale price.</p>

<p className="text-xs md:text-sm xl:text-base text-white">8.3. Auction. You may enter into an auction transaction whereby we have listed such NFTs for sale on the marketplace via an auction process. A bid placed in an auction constitutes a binding offer that may only be revoked before it is accepted. Acceptance of your bid occurs if, at the close of the auction, your bid is the highest and no further bids are placed that surpass your offer. By participating in the auction, you agree to honor your bid if it is accepted under these circumstances.</p>

<p className="text-xs md:text-sm xl:text-base text-white">The Company may establish a specific start and end time for an auction, which will be clearly displayed. Auction timers are set to operate accurately; however, slight discrepancies may occur due to technical limitations, and users are encouraged to place their bids in a timely manner. The NFT will be awarded to the highest bidder at the end of the auction period, provided the bid meets any reserve price set by the Company.</p>

<p className="text-xs md:text-sm xl:text-base text-white">Auction participants are expressly prohibited from engaging in deceptive practices, including but not limited to manipulating auction outcomes, artificially inflating or deflating NFT prices (e.g., &quot;wash trading&quot;), or employing any other anticompetitive behaviors, such as & puffing,&  & chill bidding,&  & shill bidding,&  & sham bidding,&  or & sock puppet bidding.&  Participants acknowledge and accept all risks associated with initiating or participating in an auction, including technical or transactional errors that may arise.</p>

<p className="text-xs md:text-sm xl:text-base text-white">8.4. The NFTs can be resold to any third parties. Any revenue earned in the marketplace for sales of the NFTs, minus any Gas Fees and Commission, shall be paid to you on the Blockchain by the purchaser of your NFT.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> OWNERSHIP AND MANAGEMENT OF DIGITAL ASSETS, NFTs, AND CONTENT CREATED BY USERS. 9.1. Ownership. The owner of an NFT obtains an exclusive license to use the NFT in the Game world. This right includes the right to charge other players for certain access to the in-game SKINS as NFT represented by and tied to the NFT. Each piece of a NFT represented by an NFT carries certain attributes as described on the Site. Each NFT owner decides what can be do and play in the game with their NFT and may impose their own terms and conditions and policies (which shall not conflict with these Terms). A skin can be: characters, clothes, weapons, abilities, animations, attacks and more.</p>

<p className="text-xs md:text-sm xl:text-base text-white">9.2. Rights. When an NFT Skin is bought by a wallet, the controller of that wallet has an exclusive license to possess and use the skin associated with the NFT in the Game world. The relevant skin will have the features of the skin based on its tier and any efforts expended on the in-game skin by the NFT owner. The absolute ownership of the in-game skin lies at all times with the Company, who licenses the right to possess and use the land and makes it available with the attributes applicable to the tier to which the skin belongs in the game world. The Company grants to the purchaser a non exclusive, worldwide, non-sublicensable without Company consent, royalty-free license to use and display any intellectual property that resides in the NFTs. The secondary market the company Katana Inu will take a % that will be different per Skin probably betwee 5-20% of the secondary sell.</p>

<p className="text-xs md:text-sm xl:text-base text-white">9.3. Content: Subject to compliance with applicable laws and regulations, Users grant to the Company, its affiliates, and successors a non-exclusive, worldwide, assignable, sub-licensable, unlimited, and royalty-free license to use, copy, display, perform, reproduce, and distribute content created by the Users in relation to the NFTs for the following specific purposes:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Operation, promotion, sharing, development, marketing, and advertising of Katana Inu, the Site, or any other purpose directly related to the Katana Inu ecosystem. Displaying or performing the content on the Site, third-party platforms, social media posts, blogs, or publicly accessible media. Creating and distributing derivative works based on the content created by Users and associated with the NFTs issued by the Company. This license does not grant the Company any right to sell or otherwise commercially exploit the User's content outside the specific purposes stated herein unless separately agreed with the User.</p>

<p className="text-xs md:text-sm xl:text-base text-white">In accordance with EU copyright law, any use of the content that generates direct revenue for the Company beyond the outlined purposes will entitle the User to fair compensation, as determined by applicable law. Users retain all moral and economic rights to their content except as expressly granted herein.</p>

<p className="text-xs md:text-sm xl:text-base text-white">For any royalties arising from transactions on third-party marketplaces involving NFTs, the Company acknowledges that such royalties are governed by the respective marketplace's terms and conditions, and the Company will have no control or obligation over such payments unless explicitly stated.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> Game Tokens, Rewards , Staking Program and User Responsibilties 10.1 In-Game Tokens and Utility. The KATA Token is the designated utility token within the Katana Inu ecosystem, offering players access to a range of in-game benefits and features. These include, but are not limited to, VIP status, Skin VIP access, daily rewards, and other gameplay-related advantages. To access these benefits, users are required to connect their digital wallet and stake the required amount of KATA Tokens, subject to the applicable staking terms as published by the Company. The utility, functionality, and scope of use of the KATA Token may be amended from time to time to reflect ongoing game development updates and evolving regulatory requirements. At all, this staking is not a must, it can also be just holding & KATA&  tokens in their wallets to & earn&  & KATA&  tokens. This can be changed time to time from staking or just holding. Without holding KATA tokens, there is no Earn system.</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.2 Weekly Event Rewards. As part of our community engagement, players may earn KATA Token rewards for their participation in regular in-game events, such as weekly tournaments, missions, or gameplay achievements. Rewards may also be granted based on player rankings, leaderboard positions, or performance during seasonal campaigns and event-specific criteria published by the Company.</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.3 From Tier to Tier, means from Level to Level the player can probably earn more if the level is higher, and if holding more Tokens and more NFTs the earnings might be higher.</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.4 Burn System, we are able to burn tokens by kills in the game or generell events on Tournaments etc. This is also a utility of KATA token.</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.5 Staking Terms. Katana Inu offers staking opportunities that allow players to stake KATA Tokens to unlock additional benefits such as VIP access or expanded land slots within the Game. Participation in these staking programs is voluntary and governed by separate staking terms and conditions, accessible at:</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.6 Regulatory Flexibility Disclaimer. Please note that digital token regulations vary by jurisdiction and are evolving rapidly. The Company reserves the right to modify Token structures, utility, and distribution logic to remain compliant with applicable laws. No part of this section should be interpreted as a guarantee of KATA Token value or exchangeability outside the Game ecosystem.</p>

<p className="text-xs md:text-sm xl:text-base text-white">10.7 User Responsibility for Digital Wallets. The Company shall not be held liable for the security, management, access, or maintenance of any digital wallet used by you in connection with the Game. You are solely responsible for the protection of your wallet credentials, including but not limited to private keys, passwords, and recovery phrases. The Company does not store, manage, or have the ability to recover lost or compromised wallet information. All transactions, including the purchase, sale, or transfer of digital assets, are executed directly on the blockchain and are irreversible. By using the platform, you acknowledge and accept that any loss, unauthorized access, or failure related to your wallet& whether due to hacking, phishing, user error, or mismanagement& is solely your responsibility. Users are strongly advised to utilize reputable wallet providers and adopt best practices for securing digital assets.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> PROHIBITED ACTIVITIES. 11.1 You may only use the Services for lawful purposes. You must not use the Services to or for:</p>

<p className="text-xs md:text-sm xl:text-base text-white">In any way that breaches any applicable local, national or international law or regulation, and/or in any way that is unlawful or fraudulent or has any unlawful or fraudulent purpose or effect. Misuse our system or this Site. In particular, you must not damage, disable, disrupt, hack into, unduly burden, circumvent security or otherwise disrupt the operation and security related features of our system and/ or the Site, or attempt to carry out any of the foregoing, in any way for any reason. This includes introducing viruses, trojans, worms, logic bombs or other material which is or could be malicious or technologically harmful. Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services or copy or adapt the offering& s software in anyway. Attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site. Make any unauthorized use of the Site or creating user accounts by automated means or under false pretenses. Use or attempt to use any automated program (including, without limitation, any spider, web crawler, data mining, robots, or similar data gathering and extraction tools) and/ or scraping technology to access our system or this Site. Any such use or attempted use of an automated program and/ or scraping technology shall be a misuse of our system and this Site. Obtaining access to any part of our system or this Site by means of any such automated programs and/ or scraping technology is strictly unauthorized. Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us. Harass, annoy, intimidate, or threaten any other users or our employees or agents engaged in providing any portion of the Site to you. Use the Site in a manner inconsistent with any applicable laws or regulations. Building public tools and bots that facilitate transparency and analysis. Abusing public APIs by spamming requests for purposes other than those expressly permitted, such as legitimate transparency and analysis, will result in the offending user being permanently banned from using such APIs in the future.</p>

<p className="text-xs md:text-sm xl:text-base text-white">Unauthorized access to private APIs, including for the purpose of data retrieval or analytical storage, is strictly prohibited. Private APIs are for internal use or approved partnerships only. Unauthorized access will lead to immediate suspension or legal action.</p>

<p className="text-xs md:text-sm xl:text-base text-white">11.2. You must not conduct any Prohibited Activity listed above. We reserve the right to block your account and access to the Game, the Site, or the App if we find you in violation of this section.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> INTERNATIONAL USERS. 12.1. The Services are operated by the Company, Katana Marketplace, Katana Marketplace Ltd c/o Craigmuir Chambers Road Town, Tortola VG 1110 BRITISH VIRGIN ISLANDS, which retains ownership of the intellectual property.</p>

<p className="text-xs md:text-sm xl:text-base text-white">The Services are not intended to subject the Company to the laws or jurisdiction of any state, country, or territory other than that of the British Virgin Islands (solely in relation to intellectual property). The Company makes no representation or warranty that the Site or any part thereof is appropriate or available for use in any particular jurisdiction outside of these locations. Those who choose to access the Site do so on their own initiative and at their own risk and are responsible for complying with all local laws, regulations, and requirements.</p>

<p className="text-xs md:text-sm xl:text-base text-white">Users are also responsible for complying with BVI export controls, where applicable, including any embargoes or other restrictions on exports. The Company reserves the right to limit the availability of the Site and Services, in whole or in part, to any person, geographic area, or jurisdiction, at any time and at its sole discretion.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> WEBSITES WE LINK TO. 13.1. This Site may contain links to websites operated by third parties. The Company does not endorse or assume responsibility for the accuracy, content, products, services, or practices of any linked third-party websites. While these links are provided for your convenience, your use of any linked third-party website is entirely at your own risk. The Company will only provide such links where it has reviewed the third-party website for appropriateness, but this does not exempt the Company from liability under applicable laws if harm is caused by an implied endorsement. If you encounter any issues or harm from using these third-party websites, you agree to notify the Company immediately.</p>

<p className="text-xs md:text-sm xl:text-base text-white">13.2. Please note that payment methods may involve the use of third-party payment service providers. These service providers may charge you additional fees when processing payments in connection with the payment services, and Company is not responsible for any such fees and disclaims all liability in this regard. Your payment method may also be subject to additional terms and conditions imposed by the applicable third-party payment service provider; please review these terms and conditions before using your payment method.</p>

<p className="text-xs md:text-sm xl:text-base text-white">13.3. YOU AGREE THAT YOUR USE OF ANY THIRD-PARTY WEBSITES AND RESOURCES, INCLUDING ACCESSING THEIR CONTENT, INFORMATION, DATA, ADVERTISING, PRODUCTS, OR OTHER MATERIALS, IS SUBJECT TO THE TERMS AND CONDITIONS AND PRIVACY POLICIES OF THOSE THIRD-PARTY WEBSITES. THE COMPANY SHALL NOT BE LIABLE FOR ANY DAMAGES, LOSSES, OR DISPUTES ARISING FROM YOUR USE OF SUCH WEBSITES, EXCEPT WHERE LIABILITY CANNOT BE EXCLUDED UNDER APPLICABLE LAW.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> LINKING TO OUR SITE. 14.1. You may link to our home page, provided you do so in a manner that, in our sole discretion, is appropriate, legal, and does not damage our reputation or exploit it for personal or commercial gain. The link must not create any form of association, approval, or endorsement on our part where none exists. You may not establish a link from any website that you do not own or control. Framing our Site on any other website or creating a link to any specific part of our Website without prior written permission from us is strictly prohibited.</p>

<p className="text-xs md:text-sm xl:text-base text-white">The website from which you are linking must comply fully with our acceptable use policy and must not host content that:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Violates any applicable laws or regulations. Contains defamatory, obscene, offensive, or otherwise objectionable material. Promotes illegal activities or infringes upon the rights of any third party. 14.2. We reserve the right to withdraw linking permission without notice and without giving a reason.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> SUBMISSIONS. You acknowledge and agree that the Company does not solicit or seek any unsolicited ideas, questions, comments, suggestions, improvements, enhancements, recommendations, or feedback regarding the provision of the Services (& Submissions& ). However, if you voluntarily provide us with any such Submissions via direct mail, email, or other means, you agree to grant the Company a global, unlimited, irrevocable, non-exclusive, and royalty-free license to use, reproduce, perform, display, adapt, modify, or otherwise exploit such Submissions for any lawful purpose, whether commercial or non-commercial, in any manner the Company deems appropriate. The Company shall treat all Submissions as non-confidential and, subject to the license granted, will have sole discretion over their use and dissemination.</p>

<p className="text-xs md:text-sm xl:text-base text-white">You represent and warrant that:</p>

<p className="text-xs md:text-sm xl:text-base text-white">You have the legal right to make the Submissions and grant the license described above. The Submissions are original to you, or you have obtained all necessary permissions or rights from any third party prior to submission. For clarity, the Company does not assert sole ownership of the intellectual property rights in your Submissions but is granted the unrestricted license described above. To the extent permissible under applicable law, you waive any claims for attribution or compensation related to the use of your Submissions.</p>

<p className="text-xs md:text-sm xl:text-base text-white">The Company recognizes that moral rights may not be waived in certain jurisdictions and agrees to use Submissions in a manner that respects the creator& s moral rights, as required by applicable law.</p>

<p className="text-xs md:text-sm xl:text-base text-white">You further agree that there will be no recourse against the Company for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions, provided the Company uses the Submissions in accordance with the license granted herein.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> YOUR REPRESENTATIONS &  WARRANTIES. 17.1. You represent and warrant that you are at least 18 years of age or are of the legal age to form binding contract under the applicable laws to register.</p>

<p className="text-xs md:text-sm xl:text-base text-white">17.2. You represent and warrant that you possess the legal authority to enter these Terms and to use the Services in accordance with all terms and conditions herein.</p>

<p className="text-xs md:text-sm xl:text-base text-white">17.3. You represent and warrant that all personal data provided by you in connection with the Services is up to date, complete, accurate and true. In case of a change, you undertake to provide us notice in a timely manner. You authorize us to verify the accuracy of the personal data that you have provided to create your Account, and any other information you provide to us. You undertake to cooperate with us during such verification process.</p>

<p className="text-xs md:text-sm xl:text-base text-white">17.4. You represent that you are legally permitted to use the Services in your jurisdiction including owning the NFTs and interacting with the Services in any way. You further represent that you are responsible for ensuring compliance with applicable laws of your jurisdiction and acknowledge that the Company is not liable for your compliance or failure to comply with such laws. You further represent and warrant that all funds or assets used by you have been lawfully obtained by you in compliance with all applicable laws.</p>

<p className="text-xs md:text-sm xl:text-base text-white">17.5. Where you register for an account with us, you represent and warrant the following:</p>

<p className="text-xs md:text-sm xl:text-base text-white">Each registration is for a single user only. You undertake that all information provided by you for the purposes of registering with us is correct, accurate and complete. You agree not to provide any other person with access to this Site or any part of the Site with your credentials. You accept sole responsibility for keeping your registration and account information confidential and you must not disclose it to any other person or entity. You accept sole responsibility for the use of your account, which is for your personal use only and will be held responsible for any unauthorized use of your account. You agree to ensure that you exit from your account at the end of each session. You will notify us immediately of any unauthorized use of them or any other breach of security of this Site of which you become aware. You will not access the Site, the App and the Smart Contracts through automated and non-human means, whether through a bot, script or otherwise. You will not use the Site, the App, and the Smart Contracts for any Prohibited Activities as listed in Article 11. Your use of the Site, the App, and the Smart Contracts will not violate any applicable law or regulation. If we have reasonable grounds to believe that any information provided by you is untrue, expired, inaccurate, not current, or incomplete, we reserve the right to suspend your account by sending you a notice demanding correction within a reasonable amount of time. During the time provided within the demand for correction , we further reserve the right to suspend all access to the Services we provide to you. You (a human being) agree to use only one in-game account to participate in activities that earn tokens or other rewards during any 24-hour period. & Tokens&  refers to in-game digital assets, including but not limited to cryptocurrency or in-game points, earned through gameplay or activities within the App. The specifics of token earning and usage, including applicable limits, are described in detail in the relevant game documentation available on the Site. You, as a NFT owner, are responsible for the actions of any users or players using any the NFT you own, that play on your behalf, and that their actions can have consequences for any connected accounts that you own. You have not been included in any trade embargoes or economic sanctions list (such as United Nations Security Council Sanctions list), the list of specially designated nationals maintained by OFAC (the Office of Foreign Assets Control of the U.S. Department of the Treasury), or the denied persons or entity list of the U.S. Department of Commerce.</p>

<p className="text-xs md:text-sm xl:text-base text-white">COMPANY& S REPRESENTATIONS &  WARRANTIES. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY DISCLAIMS ANY EXPRESS, IMPLIED, OR STATUTORY WARRANTIES NOT EXPLICITLY SET FORTH IN THESE TERMS. THIS INCLUDES, BUT IS NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE, OR TRADE USAGE.</p>

<p className="text-xs md:text-sm xl:text-base text-white">THE SERVICES ARE PROVIDED ON AN & AS IS&  AND & AS AVAILABLE&  BASIS, AND THE COMPANY DOES NOT GUARANTEE THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE. IF THE SERVICES FAIL TO MEET THEIR INTENDED PURPOSE DUE TO REASONS WITHIN THE COMPANY& S CONTROL, THE COMPANY WILL ENDEAVOR TO RESOLVE SUCH ISSUES PROMPTLY AND EFFECTIVELY, SUBJECT TO THE LIMITATIONS SET FORTH IN THESE TERMS AND APPLICABLE LAWS.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> DISCLAIMERS. 19.1. WITHOUT LIMITING THE FOREGOING, COMPANY, ITS AFFILIATED ENTITIES AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EQUITY HOLDERS, EMPLOYEES, CONSULTANTS, AGENTS, REPRESENTATIVES, LICENSORS AND PROVIDERS MAKE NO REPRESENTATION OR WARRANTY (A) REGARDING THE STATEMENTS, ACTS OR OMISSIONS OF ANY THIRD PARTIES; (B) THAT THE SITE AND/OR ANY OF ITS FEATURES WILL BE AVAILABLE ON A TIMELY BASIS, OR THAT ACCESS TO THE SITE AND/OR ANY OF ITS FEATURES WILL BE UNINTERRUPTED OR SECURE; (C) THAT DEFECTS OR ERRORS WILL BE CORRECTED; OR (D) THAT THE SITE OR THE SERVERS OR NETWORKS THROUGH WHICH THE SITE IS MADE AVAILABLE ARE SECURE OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.2. WE DO NOT GUARANTEE THAT OUR SITE, OR ANY CONTENT ON IT, WILL ALWAYS BE AVAILABLE OR BE UNINTERRUPTED. WE MAY SUSPEND, WITHDRAW OR RESTRICT THE AVAILABILITY OF ALL OR ANY PART OF OUR SITE FOR BUSINESS AND OPERATIONAL REASONS. YOU ARE ALSO RESPONSIBLE FOR ENSURING THAT ALL PERSONS WHO ACCESS OUR SITE THROUGH YOUR INTERNET CONNECTION ARE AWARE OF THESE TERMS AND OTHER APPLICABLE TERMS AND CONDITIONS, AND THAT THEY COMPLY WITH THEM. FURTHER, WE DO NOT PROMISE THAT THE SITE, NOR ANY INFORMATION, CONTENT OR MATERIALS MADE AVAILABLE THROUGH THE SITE, WILL BE ACCURATE, RELIABLE, COMPLETE, ERROR FREE OR COMPATIBLE WITH ANY PARTICULAR HARDWARE OR SOFTWARE.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.3. THE NFTS ARE INTANGIBLE DIGITAL ASSETS THAT EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE BLOCKCHAIN. ALL SMART CONTRACTS ARE CONDUCTED AND OCCUR ON THE DECENTRALIZED LEDGER WITHIN THE POLYGON NETWORK. THE COMPANY HAS NO CONTROL OVER AND MAKES NO GUARANTEES OR PROMISES WITH RESPECT TO THE OWNERSHIP RECORD OR THE SMART CONTRACTS.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.4. THE COMPANY IS NOT RESPONSIBLE FOR LOSSES DUE TO THE BLOCKCHAIN OR ANY OTHER FEATURES OF THE POLYGON NETWORK OR THE METAMASK OR OTHER ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO LATE REPORT BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN, INCLUDING FORKS, TECHNICAL NODE ISSUES, OR ANY OTHER ISSUES HAVING FUND LOSSES AS A RESULT.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.5. THE COMPANY, ITS AFFILIATED ENTITIES AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EQUITY HOLDERS, EMPLOYEES, CONSULTANTS, AGENTS, REPRESENTATIVES, LICENSORS AND PROVIDERS WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF THE BLOCKCHAIN OR METAMASK OR ANY OTHER ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISIGN FROM: (A) USER ERROR, SUCH AS FORGOTTEN PASSWORDS OR INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) INTELLECTUAL PROPERTY INFRINGEMENT BY USERS; (E) UNAUTHORIZED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING BUT NOT LIMITED TO THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICES, THE BLOCKCHAIN, OR THE METAMASK OR OTHER ELECTRONIC WALLET.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.6. The content on the Site is provided for general information only and does not constitute specific advice. We do not warrant the accuracy, completeness or usefulness of this information. You must obtain professional or specialist advice before taking, or refraining from taking, any action based on the content on the Site. In particular, images and videos on the Site, whilst displayed in good faith, are for information purposes only and we do not accept any liability or responsibility for their accuracy. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Site, or by anyone who may be informed of any of its contents.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.7. It is the sole responsibility of prospective Users to satisfy themselves as to the accuracy of any information displayed on the Site and the responsibility of Users to ensure the accuracy of content provided on the Site and in any other documentation or information. Any reliance you place on such information is strictly at your own risk.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.8. Although we make reasonable efforts to update the information and content on the Site, we make no representations, warranties or guarantees, whether express or implied that the information and content on the Site is accurate, complete or up to date at any time.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.9. Any purchases you make through third-party websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third-party.</p>

<p className="text-xs md:text-sm xl:text-base text-white">19.10. The Site is operated by Katana Inu Operating Limited, a company incorporated in the British Virgin Islands, under license from Katana Marketplace LTD., a company incorporated in BVI which holds ownership of the underlying intellectual property. The Company makes no representations that the Site or any of its content is appropriate or legally accessible in jurisdictions outside of the British Virgin Islands.</p>

<p className="text-xs md:text-sm xl:text-base text-white">If you access the Site from outside of these jurisdictions, you do so on your own initiative and are solely responsible for compliance with all applicable local laws. Access to the Site may be restricted or prohibited for certain persons or in certain countries, and the Company disclaims any liability for such access in violation of applicable laws.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> INDEMNIFICATION. 20.1. To the extent permitted by law, you agree to defend, indemnify and hold harmless, us and our subsidiaries, affiliates, licensors, employees, agents, third-party information providers, and independent contractors against any claims, damages, costs, liabilities and expenses (including, but not limited to, reasonable attorneys&  fees) arising out of or related to your conduct, your use or inability to use the Site, your breach of these Terms.</p>

<p className="text-xs md:text-sm xl:text-base text-white">20.2. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding, which is subject to this indemnification upon becoming aware of it.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> LIMITATION OF LIABILITY. 21.1. Company shall not be liable for any claim or demand made against User by any third party except to the extent such claim or demand relates to rights conferred to User under these Terms and Conditions.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.2. Company does not exclude or limit in any way liability to where it would be unlawful to do so. This includes liability for death or personal injury caused by our negligence or the negligence of our employees, agents or subcontractors and for fraud or fraudulent misrepresentation.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.3. We will not be liable for any loss or damage caused by a virus, distributed denial of service attack or other technologically harmful material caused to your information technology, devices, computer programs, platform, data or other proprietary material arising in connection with your use of our Site and/ or Services or to your downloading of any content on it, or any website linked to it.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.4. We will not be liable for any failures, due to software or internet errors or unavailability, or any other circumstances beyond our reasonable control.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.5. We may put in place such systems as we from time to time, to prevent automated programs from being used to obtain unauthorized access to our system and this Site. We shall not be liable to you for any consequences arising out of, or in connection with any such use or attempted use of automated programs to obtain unauthorized access to our system or this Site.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.6. You agree and acknowledge that we do not endorse the products or services offered on third-party websites and you shall hold us harmless from any harm caused by your purchase of such products or services. Additionally, you shall hold us harmless from any losses sustained by you or harm caused to you relating to or resulting in any way from any third-party content or any contact with third-party websites.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.7. Please note that we only provide our Site for domestic and private use. You agree not to use our Site for any commercial or business purposes, and we have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.8. We will not be liable to you for any loss or damage, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, even if foreseeable, arising under or in connection with use of, or inability to use, or use of or reliance on any content displayed on our Site. In particular, we will not be liable for loss of profits, sales, business, or revenue, business interruption, loss of anticipated savings, loss of business opportunity, goodwill or reputation; or any indirect or consequential loss or damage.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.9. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THESE TERMS AND TO THE EXTENT PERMITTED BY LAW, IN THE EVENT THAT WE ARE DETERMINED TO BE LIABLE TO YOU FOR ANY CAUSE, YOU EXPRESSLY AGREE THAT OUR MAXIMUM LIABILITY FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING WITHOUT LIMITATION NEGLIGENCE) OR OTHERWISE SHALL BE LIMITED TO THE GREATER OF (A) THE AMOUNTS PAID BY YOU TO US TO ACCESS AND USE THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THE DATE THE CLAIM AROSE, OR (B) ONE HUNDRED (100) US DOLLAR.</p>

<p className="text-xs md:text-sm xl:text-base text-white">21.10. IT IS POSSIBLE THAT APPLICABLE LAW MAY NOT ALLOW FOR LIMITATIONS ON CERTAIN IMPLIED WARRANTIES OR EXCLUSIONS OR LIMITATIONS OF CERTAIN DAMAGES; SOLELY TO THE EXTENT THAT SUCH LAW APPLIES TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> ASSUMPTION OF RISK. You accept and acknowledge each of the following:</p>

<p className="text-xs md:text-sm xl:text-base text-white">a) The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the value of your NFTs, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of the NFTs will not lose money.</p>

<p className="text-xs md:text-sm xl:text-base text-white">b) You are solely responsible for determining what, if any, taxes apply to your NFTs related transactions. The Company is not responsible for determining the taxes that apply to your transactions on the App.</p>

<p className="text-xs md:text-sm xl:text-base text-white">c) There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that the Company will not be responsible for any communication failures, disruptions or delays you may experience when using the Polygon network, however caused.</p>

<p className="text-xs md:text-sm xl:text-base text-white">d) The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Company& s ecosystem, and therefore the potential utility or value of the NFTs.</p>

<p className="text-xs md:text-sm xl:text-base text-white">e) Upgrades to the Polygon network may have unintended, adverse effects on the NFTs.</p>

<p className="text-xs md:text-sm xl:text-base text-white">f) You acknowledge and agree that cryptography and cryptocurrency is a progressing field. Advances in code cracking or technical advances such as the development of quantum computers may represent risks to the Smart Contracts and the Services which could result in the theft or loss of your NFTs, or any other potential consequences. By using the Services, you acknowledge and agree to undertake these risks.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> RESOLVING DISPUTES. 22.1 All matters relating to these Terms and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims) shall, except where otherwise stated, be governed by and construed in accordance with the laws of the British Virgin Islands, without reference to conflict of laws.</p>

<p className="text-xs md:text-sm xl:text-base text-white">22.2 Any dispute, difference, controversy, or claim arising out of or in connection with these Terms& including their existence, validity, interpretation, performance, termination, or remedies& excluding disputes related to intellectual property rights, shall be referred to and finally resolved by arbitration administered by the BVI International Arbitration Centre (BVI IAC) under its applicable rules in force at the time arbitration is commenced. The seat of arbitration shall be the British Virgin Islands, the language of the arbitration shall be English, and the tribunal shall consist of one (1) arbitrator appointed in accordance with such rules. The award of the arbitrator shall be final and binding. The parties agree to keep all matters relating to such arbitration confidential.</p>

<p className="text-xs md:text-sm xl:text-base text-white">22.3 Any dispute relating directly to intellectual property rights, including but not limited to ownership, infringement, licensing, or use of proprietary content, shall be governed by the laws and referred to arbitration administered by the BVI International Governement) in accordance with its rules in force at the time of commencement. The seat of arbitration shall be BVI, and the language shall be English. A single arbitrator shall be appointed, and the award shall be final and binding.</p>

<p className="text-xs md:text-sm xl:text-base text-white">22.4 Notwithstanding the above, we retain the right to bring any urgent suit, action, or proceeding against you for any actual or threatened breach of these Terms in your place or country of residence or any other relevant jurisdiction, if we determine that urgent injunctive or equitable relief is required. You waive any and all objections to the exercise of jurisdiction by such courts and to venue in such courts.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> TERMINATION AND SUSPENSION. 24.1. You have the right to terminate your account at any time by canceling and discontinuing your access to and use of the Services. If you terminate your account due to a breach of these Terms by the Company, you may be entitled to a refund of any unused funds or services, subject to applicable laws and the circumstances of the termination. The Company reserves the right to terminate your account without prior notice only in cases of extreme breaches or illegal activities, in which case no refund shall be due. In all other cases of termination by the Company, reasonable notice will be provided, and any refund entitlements will be evaluated in compliance with applicable law.</p>

<p className="text-xs md:text-sm xl:text-base text-white">24.2. In the event of your breach of these Terms or any suspected fraudulent, abusive, or illegal activity, the Company may, without limitation, suspend your account, block any infringing content, and adopt any other action deemed necessary to prevent future breaches, in addition to any other remedies the Company may have at law or in equity.</p>

<p className="text-xs md:text-sm xl:text-base text-white">24.3. Upon the termination or suspension of your account, you may no longer have access to the information or content associated with your account. However, the Company will retain such data for up to 30 days following the termination to allow users to exercise any data access or portability rights under GDPR or other applicable laws. Upon completion of the 30-day period, the Company will delete the data unless otherwise required by law.</p>

<p className="text-xs md:text-sm xl:text-base text-white">24.4. If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or a borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> MODIFICATION TO THESE TERMS. 25.1. From time to time, we may revise, amend, or supplement these Terms as necessary to address specific pre-agreed areas, including changes required to comply with applicable laws, enhance user functionality, or address technical improvements. Any proposed changes will be communicated to users via their registered email address and published prominently on the main page of the Site. Users will be provided with a minimum notice period of 30 days to review the updated Terms. During this period, users may accept the revised Terms or, if they do not agree, terminate their account without penalty. Continued use of the Site or Services after the effective date of the changes will constitute your acceptance of the revised Terms.</p>

<p className="text-xs md:text-sm xl:text-base text-white">25.2. Changes to these Terms will only become effective upon the expiration of the notice period and after users have had the opportunity to review and accept them. The Company will notify users of such changes by email and by updating the & Last Updated&  date of these Terms. Users who do not wish to accept the revised Terms may notify the Company during the notice period to terminate their use of the Services without incurring penalties. No changes will be considered binding unless they have been explicitly communicated to the user and acknowledged.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> ASSIGNMENT. We may transfer, assign, sublicense, or pledge in any manner whatsoever, any of our rights and obligations under these Terms to any third party. In such an event, we will provide notice of the transfer or assignment to your registered email address and publish the notice on the main page of the Site. You acknowledge and agree that such transfer or assignment will not relieve you of your obligations under these Terms. Your continued use of the Site and Services after receiving such notice will constitute your acceptance of the transfer or assignment.</p>

<p className="text-xs md:text-sm xl:text-base text-white"> MISCELLANEOUS. 27.1. You agree that these Terms will not be construed against us by virtue of us having drafted them.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.2. Any heading, caption or section title contained herein is inserted only as a matter of convenience, and in no way defines or explains any section or provision hereof.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.3. No delay or failure by us to enforce any provision of the Terms will be deemed a waiver or create a precedent or will prejudice our rights.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.4. By using the Services, you agree to be bound by these Terms, and to the extent that any or all terms of these Terms are inconsistent with any agreement, written or oral, you may have previously or contemporaneously entered into and/or signed with Company with respect to the subject matter herein, you acknowledge and agree that the terms of these Terms shall supersede such other agreement and prevail.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.5. If any provision in these Terms is deemed unlawful, void, or for any reason unenforceable, then that provision shall be enforced to the maximum extent permissible, and the remainder of the Terms shall remain in full force and effect.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.6. These Terms and any policies posted by us on the Site constitute the entire agreement and understanding between you and us.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.7. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms or use of the Site.</p>

<p className="text-xs md:text-sm xl:text-base text-white">27.8. Without limitation, you agree that a printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>

<p className="text-[#f5a238] font-medium text-sm md:text-base xl:text-lg"> CONTACT US. If you have any questions or concerns, including if you need to access these Terms in an alternative format, we encourage you to contact us via e-mail at support@katanainu.com.</p>
      </div> 
    </div>
  );
};


// [#f5a238]
